import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {gql, GraphQLClient} from "graphql-request";
import BlogCard from "../components/BlogCard";

const graphcms = new GraphQLClient(
  "https://api-ap-northeast-1.graphcms.com/v2/cl3sdrv2ma0w701xkhm0pbk2r/master"
);

const QUERY = gql`
{
  posts(orderBy: datePublished_DESC) {
    id
    title
    datePublished
    slug
    content {
      html
    }
    author {
      name
      avatar {
        url
      }
    }
    coverPhoto {
      publishedAt
      createdBy {
        id
      }
      url
    }
  }
}
`

export async function getStaticProps() {
  const {posts} = await graphcms.request(QUERY);
  return {
    props: {
      posts
    },
    revalidate: 30
  }
}

export default function Home({posts}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bloggy</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className={styles.main}>
        {posts.map((post) => (
          <BlogCard key={post.id} {...post}/>
        ))}
      </main>
    </div>
  )
}
